version: '3.1'
services:
    webserver:
        container_name: olx-web
        image: 'nginx:alpine'
        working_dir: /var/www/olx-crawler
        volumes:
            - '.:/var/www/olx-crawler'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'

    php-fpm:
        container_name: olx-php
        build: phpdocker/php-fpm
        working_dir: /var/www/olx-crawler
        volumes:
            - '.:/var/www/olx-crawler'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'

volumes:
  volume:
    driver: local
